name: Links (Fail Fast)

on: 
  push:
    branches:
      - master
    paths-ignore:
      - 'prisma-client-js-logo.png'
      - 'README.md'
  schedule:
    # Run “At 08:30 on Monday.”
    - cron: "30 8 * * 1"
  pull_request:
    paths-ignore:
      - 'prisma-client-js-logo.png'
      - 'README.md'

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.5.1
        with:
          fail: true
          args: --verbose --no-progress './**/*.json'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
