
name: Check links

on: 
  push:
    branches:
      - master
    paths-ignore:
      - 'prisma-client-js-logo.png'
      - 'README.md'
  schedule:
    # Run “At 08:30 on Monday.”
    - cron: "30 8 * * 1"
  pull_request:
    paths-ignore:
      - 'prisma-client-js-logo.png'
      - 'README.md'

jobs:
  markdown-link-check:
    name: Confirm redirect targets work
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-verbose-mode: 'yes'
        file-path: './_redirects'
